In [1]:
import numpy as np
from numpy import linalg

# Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1,
# 0])).


def create_array_version_1(n):
    return np.arange(n - 1, -1, -1)


def create_array_version_2(n):
    return np.arange(n)[::-1]


def create_array_version_3(n):
    return np.flip(np.arange(n))


print(create_array_version_1(10))
print(create_array_version_2(10))
print(create_array_version_3(10))


# Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

def get_diagonal_matrix_sum_1(n):
    return np.trace(np.diag(create_array_version_1(n)))


def get_diagonal_matrix_sum_2(n):
    return sum(np.diag(create_array_version_1(n)).diagonal())


def get_diagonal_matrix_sum_3(n):
    return sum(
        [np.diagflat(create_array_version_1(n))[i][i] for i in range(len(np.diagflat(create_array_version_1(n))))])


print(get_diagonal_matrix_sum_1(10))
print(get_diagonal_matrix_sum_2(10))
print(get_diagonal_matrix_sum_3(10))

# Решите систему уравнений:
# 4x + 2y + z = 4
# x + 3y = 12
# 5y + 4z = -3

array_equation_coefficient = np.array([[4, 2, 1], [1, 3, 0], [5, 4, 0]])
array_equation_result = np.array([4, 12, -3])

# version 1
print(linalg.solve(array_equation_coefficient, array_equation_result))
print(np.allclose(np.dot(array_equation_coefficient, linalg.solve(array_equation_coefficient, array_equation_result)), array_equation_result ))

# version 2
print(np.linalg.inv(array_equation_coefficient).dot(array_equation_result))
print(np.allclose(np.dot(array_equation_coefficient, np.linalg.inv(array_equation_coefficient).dot(array_equation_result)), array_equation_result ))

[9 8 7 6 5 4 3 2 1 0]
[9 8 7 6 5 4 3 2 1 0]
[9 8 7 6 5 4 3 2 1 0]
45
45
45
[-5.18181818  5.72727273 13.27272727]
True
[-5.18181818  5.72727273 13.27272727]
True
